name: CampusCar
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^0.7.0+1
  font_awesome_flutter: ^8.11.0
  flutter_svg:
  cupertino_icons: ^0.1.3
  image_picker: ^0.6.7+22
  http: ^0.12.2
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  http_parser: ^3.1.4
  fluttertoast: ^7.1.8
  hexcolor: ^1.0.6
  intl: ^0.16.1
  get_it: ^5.0.6
  flash: ^1.3.2
  flutter_material_color_picker: ^1.0.5
  firebase_storage:
  circular_check_box: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

# flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo-cc-new.png"


flutter:

  uses-material-design: true

  assets: 
    - assets/images/
    - assets/gif/

  fonts:
    - family: CarterOne
      fonts:
        - asset: assets/fonts/CarterOne-Regular.ttf
