name: CampusCar Temporary APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout source
        uses: actions/checkout@v3

      # 2️⃣ Setup JDK (for Gradle)
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'

      # 4️⃣ Cache Flutter packages
      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # 5️⃣ Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 6️⃣ Clean project
      - name: Flutter clean
        run: flutter clean

      # 7️⃣ Install dependencies
      - name: Flutter pub get
        run: flutter pub get

      # 8️⃣ Build release APK with retry (temporary-safe)
      - name: Build APK
        run: |
          retry_count=0
          max_retries=2
          until flutter build apk --release --ignore-deprecation || [ $retry_count -eq $max_retries ]; do
            retry_count=$((retry_count+1))
            echo "Build failed, retry $retry_count/$max_retries..."
            sleep 10
          done

      # 9️⃣ Upload APK artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CampusCar-APK
          path: build/app/outputs/flutter-apk/app-release.apk




