name: CampusCar APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Flutter (2.10.5 for Dart <3.0.0 support)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CampusCar-APK
          path: build/app/outputs/flutter-apk/app-release.apk
