name: CampusCar APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout source
        uses: actions/checkout@v3

      # Setup Java 17
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Setup Flutter (2.10.5 for Dart <3.0.0 support)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'

      # Cache Flutter dependencies to speed up builds
      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # Clean project
      - name: Flutter clean
        run: flutter clean

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build release APK (ignore v1 embedding deprecation)
      - name: Build APK (ignore v1 deprecation)
        run: flutter build apk --release --ignore-deprecation

      # Upload the generated APK as artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CampusCar-APK
          path: build/app/outputs/flutter-apk/app-release.apk


